[package]
name = "rusty_zip"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
ignore = "*"
windows-registry = "*"
zip = "*"
flate2 = "*"

[profile.release]
strip = true
lto = true
codegen-units = 1
