[package]
name = "rusty_zip"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
ignore = "0.4"
flate2 = "1.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
