[package]
name = "rusty_zip"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
zip = "*"
windows-registry = "*"
rust_search = "*"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
